# Generated by Django 6.1 on 2026-08-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_code', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('base_net_weight_14kt', models.DecimalField(decimal_places=3, help_text='Net gold in 14kt (grams)', max_digits=6)),
                ('diamond_weight_round_melle', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pointer_solitaire_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fancy_cut_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('color_stone_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('diamond_color', models.CharField(max_length=50)),
                ('diamond_clarity', models.CharField(max_length=50)),
                ('has_solitaire_pointer', models.BooleanField(default=False)),
                ('has_fancy_cut', models.BooleanField(default=False)),
                ('has_color_stone', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('karat', models.CharField(choices=[('14Kt', '14Kt'), ('18Kt', '18Kt')], max_length=10)),
                ('gold_color', models.CharField(choices=[('Yellow', 'Yellow'), ('Rose', 'Rose'), ('White', 'White')], max_length=10)),
                ('ring_size', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_net_weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('actual_diamond_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_color_stone_weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('report_lab', models.CharField(blank=True, max_length=50)),
                ('report_number', models.CharField(blank=True, max_length=100)),
                ('report_color', models.CharField(blank=True, max_length=50)),
                ('report_clarity', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='in_stock', max_length=20)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='catalog.product')),
            ],
        ),
    ]
