# Generated by Django 5.2.17 on 2026-08-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('sku', models.CharField(blank=True, max_length=40, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('diamond_info', models.CharField(blank=True, max_length=300)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In stock'), ('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('made_to_order', 'Made to order')], default='in_stock', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('remote_url', models.URLField(blank=True)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='catalog.product')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_color', models.CharField(choices=[('yellow', 'Yellow'), ('rose', 'Rose'), ('white', 'White')], default='yellow', max_length=10)),
                ('purity', models.CharField(choices=[('14K', '14 KT'), ('18K', '18 KT')], default='18K', max_length=6)),
                ('ring_size', models.CharField(blank=True, choices=[('5', 'Size 5'), ('5.5', 'Size 5.5'), ('6', 'Size 6'), ('6.5', 'Size 6.5'), ('7', 'Size 7'), ('7.5', 'Size 7.5'), ('8', 'Size 8'), ('8.5', 'Size 8.5'), ('9', 'Size 9'), ('9.5', 'Size 9.5'), ('10', 'Size 10'), ('11', 'Size 11'), ('12', 'Size 12'), ('13', 'Size 13')], max_length=5, null=True)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=10)),
                ('sku', models.CharField(blank=True, max_length=60, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'gold_color', 'purity', 'ring_size'), name='uniq_variant')],
            },
        ),
    ]
