# Generated by Django 6.1 on 2026-09-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', 'convert_subcategories_to_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hallmark_number',
        ),
        migrations.AddField(
            model_name='product',
            name='hallmark_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of HUID numbers (max 3)'),
        ),
    ]
