# Generated by Django 6.1 on 2026-09-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_remove_product_hallmark_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='color_stone_weight',
        ),
        migrations.RemoveField(
            model_name='design',
            name='description',
        ),
        migrations.RemoveField(
            model_name='design',
            name='fancy_cut_weight',
        ),
        migrations.RemoveField(
            model_name='design',
            name='has_color_stone',
        ),
        migrations.RemoveField(
            model_name='design',
            name='has_fancy_cut',
        ),
        migrations.RemoveField(
            model_name='design',
            name='has_solitaire_pointer',
        ),
        migrations.RemoveField(
            model_name='design',
            name='pointer_solitaire_weight',
        ),
        migrations.AddField(
            model_name='design',
            name='color_stone_weights',
            field=models.JSONField(blank=True, default=list, help_text='Array of color stone weights in carats'),
        ),
        migrations.AddField(
            model_name='design',
            name='fancy_weights',
            field=models.JSONField(blank=True, default=list, help_text='Array of fancy cut weights in carats'),
        ),
        migrations.AddField(
            model_name='design',
            name='pointer_weights',
            field=models.JSONField(blank=True, default=list, help_text='Array of pointer/solitaire weights in carats'),
        ),
    ]
