# Generated by Django 6.1 on 2026-08-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hallmark_number',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
