# Generated by Django 6.1 on 2026-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_design_color_stone_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='color_stone_rate_per_carat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per carat for color stones (e.g., rubies, emeralds)', max_digits=10),
        ),
    ]
