# Generated by Django 5.2.17 on 2026-08-09 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant_diamond_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'purity', 'gold_color']},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='uniq_variant',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ordering',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='ordering',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='productvideo',
            old_name='ordering',
            new_name='sort_order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diamond_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='remote_url',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_delta',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Badge e.g. BESTSELLER'),
        ),
        migrations.AddField(
            model_name='product',
            name='carat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total diamond weight (ct)'),
        ),
        migrations.AddField(
            model_name='product',
            name='certification',
            field=models.CharField(choices=[('IGI', 'IGI'), ('GIA', 'GIA')], default='IGI', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Strikethrough price (INR)'),
        ),
        migrations.AddField(
            model_name='product',
            name='diamond_quality',
            field=models.CharField(blank=True, choices=[('EF-VVS', 'EF - VVS (Premium Clarity)'), ('GH-VS', 'GH - VS (Fine Quality)')], default='GH-VS', max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='productimage',
            name='url',
            field=models.URLField(default='https://example.com/placeholder.jpg', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='gold_weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Selling price (INR)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='gold_color',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('White', 'White'), ('Rose', 'Rose')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='purity',
            field=models.CharField(choices=[('18Kt', '18Kt'), ('14Kt', '14Kt')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='ring_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
