# Generated by Django 6.1 on 2026-08-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_rate_14kt', models.DecimalField(decimal_places=2, help_text='INR per gram', max_digits=10)),
                ('gold_rate_18kt', models.DecimalField(decimal_places=2, help_text='INR per gram', max_digits=10)),
                ('diamond_rate_per_carat', models.DecimalField(decimal_places=2, help_text='INR per carat', max_digits=10)),
                ('making_charges_percentage', models.DecimalField(decimal_places=2, default=15.0, help_text='% of gold+diamond value', max_digits=5)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=3.0, help_text='% of total', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate Card',
                'verbose_name_plural': 'Rate Card',
            },
        ),
    ]
