# Generated by Django 6.1 on 2026-08-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ratecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstance',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('sold_offline', 'Sold Offline'), ('reserved', 'Reserved')], default='in_stock', max_length=20),
        ),
    ]
