# Generated by Django 6.1 on 2026-09-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ratecard_color_stone_rate_per_carat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecard',
            name='color_stone_rate_per_carat',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Rate per carat for color stones (e.g., rubies, emeralds)', max_digits=10),
        ),
    ]
