# Generated by Django 6.1 on 2026-08-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_hallmark_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ring_size',
            field=models.CharField(blank=True, choices=[('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20')], max_length=10, null=True),
        ),
    ]
