# Generated by Django 6.1 on 2026-08-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_ring_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_24kt_rate', models.IntegerField(blank=True, help_text='₹ per 10g of 24Kt from API', null=True)),
                ('calculated_rate', models.IntegerField(blank=True, help_text='After rounding formula', null=True)),
                ('previous_rate', models.IntegerField(blank=True, help_text='What was in DB before', null=True)),
                ('rate_applied', models.BooleanField(default=False, help_text='Did we update the rate card?')),
                ('fetch_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'gold rate histories',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, help_text='Optional link to related page', max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ratecard',
            name='auto_fetch_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic gold rate updates'),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='change_threshold_amount',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Minimum ₹ change to trigger update (when using amount threshold)', max_digits=10),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='change_threshold_percentage',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Minimum % change to trigger update (e.g., 0.50 for 0.5%)', max_digits=4),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='change_threshold_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='percentage', help_text='How to measure if rate changed enough to update', max_length=20),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='increment_percentage',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Percentage to add after rounding (e.g., 0.50 for 0.5%)', max_digits=4),
        ),
    ]
