# Generated by Django 6.1 on 2026-08-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_goldratehistory_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='last_auto_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
