# Generated by Django 6.1 on 2026-08-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_ratecard_last_auto_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='auto_fetch_interval_minutes',
            field=models.PositiveIntegerField(default=30, help_text='How often to fetch (in minutes). Set to 1 for testing.'),
        ),
    ]
