# Generated by Django 6.1 on 2026-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='making_fixed_per_gram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ratecard',
            name='making_pct_24kt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
