# Generated by Django 6.1 on 2026-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_ratecard_making_fixed_per_gram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('group', models.CharField(choices=[('style', 'Style'), ('occasion', 'Occasion'), ('material', 'Material'), ('collection', 'Collection')], default='style', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='designs', to='catalog.tag'),
        ),
    ]
