/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,jsx}",
    "./src/components/**/*.{js,jsx}",
    "./src/app/**/*.{js,jsx}",
    "./src/context/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        ivory: "#F6F6F7",
        cream: "#ECECF0",
        charcoal: "#2E3A4C",
        ink: "#2E3A4C",
        line: "#E4E4E7",
        blush: "#F2A7B3",
        gold: { DEFAULT: "#C89B3C", dark: "#A87F2C" },
      },
      fontFamily: {
        // Mapped to the CSS variables generated by next/font in layout.js
        serif: ["var(--font-playfair)", "Georgia", "serif"],
        sans: ["var(--font-poppins)", "system-ui", "sans-serif"],
      },
      boxShadow: {
        card: "0 20px 45px rgba(46,58,76,0.12)",
        hero: "0 30px 60px rgba(0,0,0,0.28)",
      },
    },
  },
  plugins: [],
};