# Generated by Django 6.1 on 2026-08-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_mto_pending',
            field=models.BooleanField(default=False, help_text='MTO item awaiting product fulfillment'),
        ),
    ]
