# Generated by Django 6.1 on 2026-09-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_ratecard_color_stone_rate_per_carat'),
        ('orders', '0005_orderitem_is_mto_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mto_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.design'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mto_diamond_grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mto_gold_color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mto_karat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mto_ring_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='catalog.product'),
        ),
    ]
